import Head from "next/head";
import { Inter } from "next/font/google";
import Hero_01 from "@/components/Hero_01";

import Calender from "@/components/Calender";
import Faq from "@/components/Faq";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ramadan Karim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero_01 />
      <Calender />
      <Faq />

    </>
  );
}
